FROM ubuntu:20.04

ENV GODOT_VERSION=3.2.3
ENV GODOT_DIST=Godot_v3.2.3-stable_linux_server.64.zip
RUN wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/${GODOT_DIST}}
RUN unzip ${GODOT_DIST}