// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuff/game_server.proto

package protobuff

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameServer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedTime          int64    `protobuf:"varint,3,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServer) Reset()         { *m = GameServer{} }
func (m *GameServer) String() string { return proto.CompactTextString(m) }
func (*GameServer) ProtoMessage()    {}
func (*GameServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_server_31933ab54e53913c, []int{0}
}
func (m *GameServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServer.Unmarshal(m, b)
}
func (m *GameServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServer.Marshal(b, m, deterministic)
}
func (dst *GameServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServer.Merge(dst, src)
}
func (m *GameServer) XXX_Size() int {
	return xxx_messageInfo_GameServer.Size(m)
}
func (m *GameServer) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServer.DiscardUnknown(m)
}

var xxx_messageInfo_GameServer proto.InternalMessageInfo

func (m *GameServer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GameServer) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

type GameServerList struct {
	GameServers          []*GameServer `protobuf:"bytes,1,rep,name=game_servers,json=gameServers" json:"game_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameServerList) Reset()         { *m = GameServerList{} }
func (m *GameServerList) String() string { return proto.CompactTextString(m) }
func (*GameServerList) ProtoMessage()    {}
func (*GameServerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_server_31933ab54e53913c, []int{1}
}
func (m *GameServerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerList.Unmarshal(m, b)
}
func (m *GameServerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerList.Marshal(b, m, deterministic)
}
func (dst *GameServerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerList.Merge(dst, src)
}
func (m *GameServerList) XXX_Size() int {
	return xxx_messageInfo_GameServerList.Size(m)
}
func (m *GameServerList) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerList.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerList proto.InternalMessageInfo

func (m *GameServerList) GetGameServers() []*GameServer {
	if m != nil {
		return m.GameServers
	}
	return nil
}

func init() {
	proto.RegisterType((*GameServer)(nil), "freemultiplay.GameServer")
	proto.RegisterType((*GameServerList)(nil), "freemultiplay.GameServerList")
}

func init() {
	proto.RegisterFile("protobuff/game_server.proto", fileDescriptor_game_server_31933ab54e53913c)
}

var fileDescriptor_game_server_31933ab54e53913c = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0x4b, 0xd3, 0x4f, 0x4f, 0xcc, 0x4d, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b,
	0x2d, 0xd2, 0x03, 0x8b, 0x0a, 0xf1, 0xa6, 0x15, 0xa5, 0xa6, 0xe6, 0x96, 0xe6, 0x94, 0x64, 0x16,
	0xe4, 0x24, 0x56, 0x2a, 0xb9, 0x72, 0x71, 0xb9, 0x27, 0xe6, 0xa6, 0x06, 0x83, 0x95, 0x08, 0xf1,
	0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x29,
	0x72, 0xf1, 0x24, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6, 0xc4, 0x97, 0x64, 0xe6, 0xa6, 0x4a, 0x30,
	0x2b, 0x30, 0x6a, 0x30, 0x07, 0x71, 0x43, 0xc5, 0x42, 0x32, 0x73, 0x53, 0xbd, 0x58, 0x38, 0x98,
	0x04, 0x98, 0x95, 0xfc, 0xb8, 0xf8, 0x10, 0xc6, 0xf8, 0x64, 0x16, 0x97, 0x08, 0xd9, 0x70, 0xf1,
	0x20, 0x59, 0x5e, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa9, 0x87, 0x62, 0xbd, 0x1e,
	0x42, 0x53, 0x10, 0x77, 0x3a, 0x9c, 0x5d, 0xec, 0xc4, 0x1d, 0xc5, 0x09, 0xf7, 0x44, 0x12, 0x1b,
	0x98, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x63, 0xa0, 0x4e, 0xf5, 0xd8, 0x00, 0x00, 0x00,
}
